##################################################################################
# Cloudify Script built in types and plugins definitions.
##################################################################################

plugins:
    script:
        executor: central_deployment_agent
        source: https://github.com/greggigon/cloudify-script-plugin/archive/1.2G.zip
